# GNU Make solution makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  cppFX_config = debug
  sandbox_config = debug
endif
ifeq ($(config),release)
  cppFX_config = release
  sandbox_config = release
endif

PROJECTS := cppFX sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

cppFX:
ifneq (,$(cppFX_config))
	@echo "==== Building cppFX ($(cppFX_config)) ===="
	@${MAKE} --no-print-directory -C cppFX -f Makefile config=$(cppFX_config)
endif

sandbox: cppFX
ifneq (,$(sandbox_config))
	@echo "==== Building sandbox ($(sandbox_config)) ===="
	@${MAKE} --no-print-directory -C sandbox -f Makefile config=$(sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C cppFX -f Makefile clean
	@${MAKE} --no-print-directory -C sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cppFX"
	@echo "   sandbox"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
